### ISSUE TITLE
Sponge Support

### ISSUE THREAD

**Issue by aikar** [aikar/TaskChain#1]
Major Issue: No API to determine isMainThread

Desire: Use PluginContainer for SpongeTaskChainFactory.create()

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/issues/897

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/f247c803524f44f2dc1431c976dca87c5789d2e9
