### ISSUE TITLE
BungeeCord support

### ISSUE THREAD

**Issue by Acquized** [aikar/TaskChain#11]
Is this possible? I tried implementing myself but I failed on the shutdown hooks (because Bungee doesn't has a proper event or shutdown method)

**Comment by MiniDigger** [comment]
if we don't find a better solution, the plugin needs to call a method on disabled manually to trigger the shutdown handlers...

**Comment by aikar** [comment]
yes, if you just call factory.shutdown in the bungee on disable that will work.

But I'm curious, how are you planning to use it in BungeeCord?

BungeeCord does not have the concept of a "Main Thread". What would .sync() do?

**Comment by aikar** [comment]
@Acquized
