### ISSUE TITLE
How do you even use this?

### ISSUE THREAD

**Issue by junebug12851** [aikar/TaskChain#19]
This project is missing pretty much all usable documentation, same for Spigot and Bukkit and Paper as well. I don't know how anybody learns how to use any of this.

I'm just trying to make a long running task in a separate thread and all I have to go on is old questions people have asked which talked about this project because there's never any proper well-written up-to-date and short and concise tutorials anywhere. A bunch of Spigot threads dumped me here and I'm still lost.

The Usage page on the wiki is all I have on how to use this and it's not even a tutorial, it's just a copy and paste blob of code that doesn't make any kind of sense at all.

Can we start with a HelloWorld tutorial that's as short and simple as possible then progressively explain each and every feature stepping me through bit by bit one at a time with each tutorial being as small, short, and simple as possible until we progress to the intermediate and then advanced stages. 

I'm never going to understand any of this without that and I don't see how anybody else can either. Why do developers almost exclusively just give a giant mutli-page blob of code and then expect everyone to figure it out on their own?

Sorry for rant, I feel like I'm climbing mount everest and back just to do the simplest things which adds days and weeks to the simplest plugins because there's almost always never any tutorials anywhere by anyone unless it's 10 years out of date and poorly written. It's often just here's a blob of code or JavaDoc, figure it out yourself.

**Comment by chickeneer** [comment]
Creating documentation takes time which is generally in short supply. 

This issue tracker does not exist for the purpose of support conversations about using TaskChain. With that being said. There is a fair amount of documentation for this project.
See...
https://github.com/aikar/TaskChain/blob/master/README.md

**Comment by aikar** [comment]
There are many examples on this page: https://github.com/aikar/TaskChain/wiki/Usage
